import pandas as pd
import numpy as np

def evaluate_consistency(file_path):
    print(f"Loading simulation results from {file_path}...")
    df = pd.read_csv(file_path)
    
    # Filter out weeks where simulation failed (valid_samples_count == 0 or NaNs)
    df_clean = df.dropna(subset=['est_fan_support_mean']).copy()
    
    results = []
    
    # Group by Season and Week to evaluate each elimination event
    grouped = df_clean.groupby(['season', 'week'])
    
    total_weeks = 0
    consistent_weeks = 0
    
    print("Evaluating consistency per week...")
    
    for (season, week), group in grouped:
        rule = group['rule_used'].iloc[0]
        
        # Determine the "Actual" eliminated contestant(s)
        # In our data structure, is_eliminated is True for the person who went home
        actual_eliminated = group[group['is_eliminated'] == True]
        
        if actual_eliminated.empty:
            continue # Should not happen if data is clean
            
        target_indices = actual_eliminated.index.tolist()
        names_eliminated = actual_eliminated['celebrity'].tolist()
        
        # Calculate "Predicted" Total Score/Rank based on the MEAN estimated fan support
        if rule == 'percent':
            # Total = Judge% + Mean Fan%
            # Lower is worse
            group['predicted_total'] = group['actual_judge_metric'] + group['est_fan_support_mean']
            
            # Predicted Eliminated = Person with Min Total
            # We handle ties by checking if the actual is in the set of mins, but usually float makes ties rare
            min_score = group['predicted_total'].min()
            # Allow for small floating point tolerance
            candidates = group[group['predicted_total'] <= min_score + 1e-9]
            predicted_names = candidates['celebrity'].tolist()
            
            # Check consistency
            # If the actual eliminated person is among the predicted candidates
            match = any(name in predicted_names for name in names_eliminated)
            
        elif rule == 'rank_simple':
            # Total = JudgeRank + Mean FanRank
            # Higher is worse (Rank 1 is best)
            group['predicted_total'] = group['actual_judge_metric'] + group['est_fan_support_mean']
            
            # Predicted Eliminated = Person with Max Total
            max_score = group['predicted_total'].max()
            candidates = group[group['predicted_total'] >= max_score - 1e-9]
            predicted_names = candidates['celebrity'].tolist()
            
            match = any(name in predicted_names for name in names_eliminated)
            
        elif rule == 'rank_save':
            # Total = JudgeRank + Mean FanRank
            # Higher is worse (Bottom 2 are at risk)
            group['predicted_total'] = group['actual_judge_metric'] + group['est_fan_support_mean']
            
            # Identify Bottom 2 (Highest 2 scores)
            # We sort descending
            sorted_group = group.sort_values('predicted_total', ascending=False)
            
            # Take top 2
            bottom_two = sorted_group.head(2)
            predicted_names = bottom_two['celebrity'].tolist()
            
            # Check consistency: Was the eliminated person in the predicted Bottom 2?
            match = any(name in predicted_names for name in names_eliminated)
            
        results.append({
            'season': season,
            'week': week,
            'rule': rule,
            'actual_eliminated': ", ".join(names_eliminated),
            'predicted_candidates': ", ".join(predicted_names),
            'consistent': match
        })
        
        total_weeks += 1
        if match:
            consistent_weeks += 1

    results_df = pd.DataFrame(results)
    
    # Calculate Accuracy Metrics
    accuracy = consistent_weeks / total_weeks if total_weeks > 0 else 0
    print(f"\nOverall Consistency Accuracy: {accuracy:.2%} ({consistent_weeks}/{total_weeks})")
    
    # Breakdown by Rule
    print("\nAccuracy by Rule Type:")
    print(results_df.groupby('rule')['consistent'].mean().apply(lambda x: f"{x:.2%}"))
    
    # Save detailed report
    output_path = 'consistency_evaluation_report.csv'
    results_df.to_csv(output_path, index=False)
    print(f"\nDetailed report saved to {output_path}")

if __name__ == "__main__":
    file_path = 'simulated_fan_votes.csv' # Assuming generated by previous script
    evaluate_consistency(file_path)
